name: Run Project Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      # This spins up a real Redis instance for your services to connect to
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio redis

      # - name: Create Dummy Image
      #   # Since your UploadService needs a file to read, we create a fake one
      #   run: test_image.jpg

      - name: Run Pytest
        # Crucial: This tells the tests where the 'src' folder is
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: pytest -v -s tests/